[package]
name = "smartplug-control"
version = "0.1.0"
edition = "2024"

[dependencies]
lid-subscriber = { version = "0.1.0", path = "../lid-subscriber" }
reqwest = { version = "0.13.1", features = ["blocking", "json"] }
serde_json = "1.0.149"
