[package]
name = "overseer"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.31.1", features = ["signal"] }
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
utils = { version = "0.1.0", path = "../utils" }
