[package]
name = "lid-publisher"
version = "0.1.0"
edition = "2024"

[dependencies]
api-types = { version = "0.1.0", path = "../api-types" }
clap = { version = "4.5.54", features = ["derive"] }
serde_json = "1.0.149"
